export const clothesAndShoesBrands = [
  { label: 'Adidas', value: 'adidas' },
  { label: 'Asics', value: 'asics' },
  { label: 'Bensimon', value: 'bensimon' },
  { label: 'Birkenstock', value: 'birkenstock' },
  { label: 'Burberry', value: 'burberry' },
  { label: 'Calvin Klein', value: 'calvin-klein' },
  { label: 'Champion', value: 'champion' },
  { label: 'Converse', value: 'converse' },
  { label: 'Diesel', value: 'diesel' },
  { label: 'Dolce & Gabbana', value: 'dolce-gabbana' },
  { label: 'Fila', value: 'fila' },
  { label: 'Gucci', value: 'gucci' },
  { label: 'Guess', value: 'guess' },
  { label: 'Hugo Boss', value: 'hugo-boss' },
  { label: 'Jack & Jones', value: 'jack-jones' },
  { label: 'Kappa', value: 'kappa' },
  { label: 'Kenzo', value: 'kenzo' },
  { label: "Levi's", value: 'levis' },
  { label: 'Lacoste', value: 'lacoste' },
  { label: 'Puma', value: 'puma' },
  { label: 'Reebok', value: 'reebok' },
  { label: 'Skechers', value: 'skechers' },
  { label: 'Superga', value: 'superga' },
  { label: 'Tommy Hilfiger', value: 'tommy-hilfiger' },
  { label: 'Vans', value: 'vans' },
  { label: 'Versace', value: 'versace' },
  { label: 'Zara', value: 'zara' },
  { label: 'Zadig & Voltaire', value: 'zadig-voltaire' },
  { label: 'Nike', value: 'nike' },
  { label: 'Autre', value: 'other' },
];
