export const meshType = [
  { label: 'Forcat', value: 'forcat' },
  { label: 'Gourmette', value: 'gourmette' },
  { label: 'Alternee', value: 'alternee' },
  { label: 'Venitienne', value: 'venitienne' },
  { label: 'Jaseron', value: 'jaseron' },
  { label: 'Grain de cafe', value: 'grainDeCafe' },
  { label: 'Marine', value: 'marine' },
  { label: 'Corde', value: 'corde' },
  { label: 'Anglaise', value: 'francaise' },
  { label: 'Cheval', value: 'cheval' },
  { label: 'Singapour', value: 'singapour' },
  { label: 'Palmier', value: 'palmier' },
  { label: 'Boules / Marseillaise', value: 'boules' },
  { label: 'Pop corn', value: 'popCorn' },
  { label: 'Haricot', value: 'haricot' },
  { label: 'Plaquette', value: 'plaquette' },
  { label: 'Serpent', value: 'serpent' },
  { label: 'Herringbone', value: 'herringbone' },
  { label: 'Américaine', value: 'americaine' },
  { label: 'Coreenne', value: 'coreenne' },
  { label: 'Autres mailles', value: 'autresMailles' },
];

export const meshWidth = [
  { label: 'Fine (moins de 3mm)', value: 'thin' },
  { label: 'Moyenne (entre 3 et 6mm)', value: 'medium' },
  { label: 'Large (plus de 6mm)', value: 'thick' },
];

export const jewleryMaterial = [
  { label: 'Argent', value: 'silver' },
  { label: 'Plaqué or', value: 'goldPlated' },
  { label: 'Plaqué argent', value: 'silverPlated' },
  { label: 'Or', value: 'gold' },
  { label: 'Platine', value: 'platine' },
  { label: 'Acier', value: 'steel' },
  { label: 'Cuivre', value: 'copper' },
  { label: 'Bronze', value: 'bronze' },
  { label: 'Pierre', value: 'stone' },
  { label: 'Verre', value: 'glass' },
  { label: 'Bois', value: 'wood' },
  { label: 'Cuir', value: 'leather' },
  { label: 'Plastique', value: 'plastic' },
  { label: 'Autre', value: 'other' },
];

export const stoneMaterial = [
  { label: 'Diamant', value: 'diamond' },
  { label: 'Rubis', value: 'ruby' },
  { label: 'Saphir', value: 'sapphire' },
  { label: 'Emeraude', value: 'emerald' },
  { label: 'Perle', value: 'pearl' },
  { label: 'Topaze', value: 'topaz' },
  { label: 'Opale', value: 'opal' },
  { label: 'Améthyste', value: 'amethyst' },
  { label: 'Turquoise', value: 'turquoise' },
  { label: 'Onyx', value: 'onyx' },
  { label: 'Jade', value: 'jade' },
  { label: 'Aigue-marine', value: 'aquamarine' },
  { label: 'Citrine', value: 'citrine' },
  { label: 'Zircon', value: 'zircon' },
  { label: 'Quartz', value: 'quartz' },
  { label: 'Autre', value: 'other' },
];

export const watchMaterial = [
  { label: 'Acier', value: 'acier' },
  { label: 'Acier inoxydable', value: 'acierInoxydable' },
  { label: 'Argent', value: 'argent' },
  { label: 'Or', value: 'or' },
  { label: 'Or rose', value: 'orRose' },
  { label: 'Or jaune', value: 'orJaune' },
  { label: 'Or blanc', value: 'orBlanc' },
  { label: 'Plaqué or', value: 'plaqueOr' },
  { label: 'Plaqué argent', value: 'plaqueArgent' },
  { label: 'Plaqué or rose', value: 'plaqueOrRose' },
  { label: 'Plaqué or jaune', value: 'plaqueOrJaune' },
  { label: 'Plaqué or blanc', value: 'plaqueOrBlanc' },
  { label: 'Laiton', value: 'laiton' },
  { label: 'Cuivre', value: 'cuivre' },
  { label: 'Aluminium', value: 'aluminium' },
  { label: 'Titane', value: 'titane' },
  { label: 'Alliage', value: 'alliage' },
  { label: 'Plastique', value: 'plastique' },
  { label: 'Autre', value: 'autre' },
];
