export const sexOptions = [
  { label: 'Homme', value: 'men' },
  { label: 'Femme', value: 'women' },
  { label: 'Unisex', value: 'unisex' },
];

export const seasonOptions = [
  { label: 'Printemps', value: 'spring' },
  { label: 'Été', value: 'summer' },
  { label: 'Automne', value: 'autumn' },
  { label: 'Hiver', value: 'winter' },
  { label: 'Toutes saisons', value: 'allSeasons' },
];

export const colorOptions = [
  { label: 'Blanc', value: 'white' },
  { label: 'Noir', value: 'black' },
  { label: 'Gris', value: 'grey' },
  { label: 'Bleu', value: 'blue' },
  { label: 'Vert', value: 'green' },
  { label: 'Jaune', value: 'yellow' },
  { label: 'Orange', value: 'orange' },
  { label: 'Rouge', value: 'red' },
  { label: 'Rose', value: 'pink' },
  { label: 'Marron', value: 'brown' },
  { label: 'Multicolore', value: 'multicolor' },
  { label: 'Cyan', value: 'cyan' },
  { label: 'Violet', value: 'violet' },
  { label: 'Incolore', value: 'colorless' },
  { label: 'Transparent', value: 'transparent' },
  { label: 'Magenta', value: 'magenta' },
  { label: 'Doré', value: 'golden' },
  { label: 'Argenté', value: 'silver' },
  { label: 'Bronzé', value: 'bronze' },
  { label: 'Autre', value: 'other' },
];

export const clothesAndAccessoriesMaterialOptions = [
  { label: 'Coton', value: 'cotton' },
  { label: 'Laine', value: 'wool' },
  { label: 'Soie', value: 'silk' },
  { label: 'Laine mérinos', value: 'merinoWool' },
  { label: 'Polyester', value: 'polyester' },
  { label: 'velours', value: 'velvet' },
  { label: 'Tulle', value: 'tulle' },
  { label: 'Laine vierge', value: 'virginWool' },
  { label: 'jersey', value: 'jersey' },
  { label: 'Denim', value: 'denim' },
  { label: 'Laine bouillie', value: 'feltedWool' },
  { label: 'jean', value: 'jean' },
  { label: 'cuir', value: 'leather' },
  { label: 'semili', value: 'leatherette' },
  { label: 'tissu', value: 'fabric' },
];

// TODO : add more options https://www.parisinfo.com/paris-pratique/informations-utiles/vie-quotidienne/poids-et-mesures-tailles-et-pointures-france

export const americanPentsSizeOptions = [
  // Tailles des pantalons américaines de 4 à 60
  { label: '4', value: '4' },
  { label: '6', value: '6' },
  { label: '8', value: '8' },
  { label: '10', value: '10' },
  { label: '12', value: '12' },
  { label: '14', value: '14' },
  { label: '16', value: '16' },
  { label: '18', value: '18' },
  { label: '20', value: '20' },
  { label: '22', value: '22' },
  { label: '24', value: '24' },
  { label: '26', value: '26' },
  { label: '28', value: '28' },
  { label: '30', value: '30' },
  { label: '32', value: '32' },
  { label: '34', value: '34' },
  { label: '36', value: '36' },
  { label: '38', value: '38' },
  { label: '40', value: '40' },
  { label: '42', value: '42' },
  { label: '44', value: '44' },
  { label: '46', value: '46' },
  { label: '48', value: '48' },
  { label: 'plus de 50', value: '50+' },
];

export const europeanPentsSizeOptions = [
  { label: '30', value: '30' },
  { label: '32', value: '32' },
  { label: '34', value: '34' },
  { label: '36', value: '36' },
  { label: '38', value: '38' },
  { label: '40', value: '40' },
  { label: '42', value: '42' },
  { label: '44', value: '44' },
  { label: '46', value: '46' },
  { label: '48', value: '48' },
  { label: '50', value: '50' },
  { label: '52', value: '52' },
  { label: '54', value: '54' },
  { label: '56', value: '56' },
  { label: 'plus de 58', value: '58+' },
];

export const universalSizeOptions = [
  { label: 'XS', value: 'XS' },
  { label: 'S', value: 'S' },
  { label: 'M', value: 'M' },
  { label: 'L', value: 'L' },
  { label: 'XL', value: 'XL' },
  { label: 'XXL', value: 'XXL' },
  { label: 'XXXL', value: 'XXXL' },
];

export const shoesAmericanSizeOptions = [
  { label: '4', value: '4' },
  { label: '4.5', value: '4.5' },
  { label: '5', value: '5' },
  { label: '5.5', value: '5.5' },
  { label: '6', value: '6' },
  { label: '6.5', value: '6.5' },
  { label: '7', value: '7' },
  { label: '7.5', value: '7.5' },
  { label: '8', value: '8' },
  { label: '8.5', value: '8.5' },
  { label: '9', value: '9' },
  { label: '9.5', value: '9.5' },
  { label: '10', value: '10' },
  { label: '10.5', value: '10.5' },
  { label: '11', value: '11' },
  { label: '11.5', value: '11.5' },
  { label: 'plus de 12', value: '12+' },
];

export const shoesEuropeanSizeOptions = [
  { label: '35', value: '35' },
  { label: '35.5', value: '35.5' },
  { label: '36', value: '36' },
  { label: '36.5', value: '36.5' },
  { label: '37', value: '37' },
  { label: '37.5', value: '37.5' },
  { label: '38', value: '38' },
  { label: '38.5', value: '38.5' },
  { label: '39', value: '39' },
  { label: '39.5', value: '39.5' },
  { label: '40', value: '40' },
  { label: '40.5', value: '40.5' },
  { label: '41', value: '41' },
  { label: '41.5', value: '41.5' },
  { label: '42', value: '42' },
  { label: '42.5', value: '42.5' },
  { label: '43', value: '43' },
  { label: '43.5', value: '43.5' },
  { label: '44', value: '44' },
  { label: '44.5', value: '44.5' },
  { label: '45', value: '45' },
  { label: '45.5', value: '45.5' },
  { label: '46', value: '46' },
  { label: '46.5', value: '46.5' },
  { label: '47', value: '47' },
  { label: '47.5', value: '47.5' },
  { label: '48', value: '48' },
  { label: '48.5', value: '48.5' },
  { label: '49', value: '49' },
  { label: '49.5', value: '49.5' },
  { label: '50', value: '50' },
  { label: 'plus de 50', value: '50+' },
];
